[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0
stdout_logfile_backups=0
loglevel=info
pidfile=/home/appuser/run/supervisord.pid
user=appuser

[program:WeKnora]
command=/app/WeKnora
directory=/app
autostart=true
autorestart=true
startretries=5
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0 # Set to 0 to disable log rotation
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=CGO_ENABLED=1
user=appuser

[unix_http_server]
file=/home/appuser/run/supervisor.sock
chmod=0700

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///home/appuser/run/supervisor.sock