kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "weknora.fullname" . }}-reader
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "weknora.labels" . | nindent 4 }}
    app.kubernetes.io/component: reader
spec:
  podSelector:
    matchLabels:
      {{- include "weknora.labels" . | nindent 6 }}
      app.kubernetes.io/component: reader
  policyTypes:
    - Ingress
    - Egress
  egress: []
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "weknora.labels" . | nindent 14 }}
              app.kubernetes.io/component: knora
      ports:
        - port: {{ .Values.reader.service.port }}
          protocol: TCP